import { Router } from 'express';
import { signup, login, userInfo, resetPassword } from '../controllers/authController.js';
import { loginValidate, signupValidate } from '../utils/validate/authValidate.js';
import { validateRequest } from '../middleware/validateRequest.js';
import limiter from '../middleware/rateLimit.js';
const router = Router();
router.post('/signup', validateRequest(signupValidate, 'body'), signup);
router.post('/login', limiter, validateRequest(loginValidate, 'body'), login);
router.get('/userInfo', userInfo);
router.post('/resetPassword', resetPassword);
export default router;
