import { Router } from 'express';
import { addCart, getCart, changeCartQuantity, deleteCart } from '../controllers/cartController.js';
import { addCartValidate, changeCartQuantityValidate, deleteCartValidate } from '../utils/validate/cartValidate.js';
import { validateRequest } from '../middleware/validateRequest.js';
const router = Router();
router.get('/', getCart);
router.post('/', validateRequest(addCartValidate, 'body'), addCart);
router.patch('/', validateRequest(changeCartQuantityValidate, 'body'), changeCartQuantity);
router.delete('/', validateRequest(deleteCartValidate, 'query'), deleteCart);
export default router;