import { Router } from "express";
import { getProduct, addProduct, addProductImage, getSellProduct, changeProductIsActive } from '../controllers/productController.js';
import { upload } from '../middleware/uploadFile.js';
import { validateRequest } from "../middleware/validateRequest.js";
import { getSellerProduct } from '../utils/validate/productValidate.js';
import { getDateItem, getSellCount, getSellOrderDetail, getSellOrders, getSumData, sellDeliver, cancelOrder } from "../controllers/sellController.js";
const router = Router();
router.get('/product', validateRequest(getSellerProduct, 'query'), getSellProduct);
router.post('/addProduct', addProduct);
router.post('/addProductImage', upload.single('file'), addProductImage);
router.patch('/changeProductIsActive', changeProductIsActive);
router.get('/getDateItem', getDateItem);
router.post('/getSumData', getSumData);
router.get('/getSellCount', getSellCount);
router.get('/getSellOrders', getSellOrders);
router.patch('/deliver', sellDeliver);
router.get('/orderDetail', getSellOrderDetail);
router.post('/cancelOrder', cancelOrder);
export default router;